name: main
on:
  push:
    branches:
      - master
      - main
      - beta
      - next
      - next-major
jobs:
  release:
    permissions:
      contents: write
      issues: write
      pull-requests: write
    runs-on:
      labels:
        - minimalistic-v2
    concurrency: release
    steps:
      - name: Checkout source
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0
      - name: Get shared actions
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          repository: 'DoodleScheduling/actions'
          ref: v3
          path: './.actions'
          token: ${{ secrets.GH_ACTIONS }}
      - uses: ./.actions/release
        with:
          token: ${{ secrets.GH_ACTIONS }}
    timeout-minutes: 45
