name: package-retention
on:
  schedule:
    - cron: '0 11 * * *'
jobs:
  package-retention:
    permissions:
      packages: write
    runs-on:
      labels:
        - minimalistic-v2
    steps:
      - name: Get shared actions
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
        with:
          repository: 'DoodleScheduling/actions'
          ref: v3
          path: './.actions'
          token: ${{ secrets.GH_ACTIONS }}
      - uses: ./.actions/package-retention
        name: Delete app images older than 90 days
        with:
          package-name: ${{ github.event.repository.name }}
          package-type: container
          age: 2160h
          container-match-tags: "[0-9a-f]{8}"
    timeout-minutes: 45
