name: pr-command
on:
  pull_request:
    types: [opened]
  issue_comment:
    types: [created]
jobs:
  slash-command:
    runs-on:
      labels: [minimalistic-v2]
    steps:
      - name: Checkout source
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
        with:
          fetch-depth: 0
      - name: Get shared actions
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
        with:
          repository: 'DoodleScheduling/actions'
          ref: v3
          path: './.actions'
          token: ${{ secrets.GH_ACTIONS }}
      - uses: ./.actions/slash-command
        with:
          token: ${{ secrets.GH_ACTIONS }}
    timeout-minutes: 45
