name: pr-close
on:
  pull_request:
    types: [closed]
jobs:
  cleanup:
    runs-on:
      labels:
        - minimalistic-v2
    timeout-minutes: 3
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
      - name: Get shared actions
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          repository: 'DoodleScheduling/actions'
          ref: v3
          path: './.actions'
          token: ${{ secrets.GH_ACTIONS }}
      - uses: ./.actions/cancel-workflow
