name: pr-command
on:
  pull_request:
    types: [opened]
  issue_comment:
    types: [created]
jobs:
  slash-command:
    runs-on:
      labels: [minimalistic-v2]
    steps:
      - name: Checkout source
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          fetch-depth: 0
      - name: Get shared actions
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          repository: 'DoodleScheduling/actions'
          ref: v3
          path: './.actions'
          token: ${{ secrets.GH_ACTIONS }}
      - uses: ./.actions/slash-command
        with:
          token: ${{ secrets.GH_ACTIONS }}
    timeout-minutes: 45
