name: pr-gitleaks
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
jobs:
  gitleaks:
    runs-on:
      labels:
        - minimalistic-v2
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          fetch-depth: 0
      - name: Get shared actions
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          repository: 'DoodleScheduling/actions'
          ref: v3
          path: './.actions'
          token: ${{ secrets.GH_ACTIONS }}
      - uses: ./.actions/gitleaks
    timeout-minutes: 45
