name: pr-stale
on:
  schedule:
    - cron: '30 1 * * *'
jobs:
  stale:
    runs-on:
      labels:
        - minimalistic-v2
    steps:
      - name: Get shared actions
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
        with:
          repository: 'DoodleScheduling/actions'
          ref: v3
          path: './.actions'
          token: ${{ secrets.GH_ACTIONS }}
      - uses: ./.actions/stale
        with:
          repo-token: ${{ secrets.GH_ACTIONS }}
    timeout-minutes: 45
