name: pr-stale
on:
  schedule:
    - cron: '30 1 * * *'
jobs:
  stale:
    runs-on:
      labels:
        - minimalistic-v2
    steps:
      - name: Get shared actions
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          repository: 'DoodleScheduling/actions'
          ref: v3
          path: './.actions'
          token: ${{ secrets.GH_ACTIONS }}
      - uses: ./.actions/stale
        with:
          repo-token: ${{ secrets.GH_ACTIONS }}
    timeout-minutes: 45
