name: renovate
on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:
  push:
    branches:
      - master
      - main
      - beta
      - next
      - next-major
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
jobs:
  renovate:
    runs-on:
      labels:
        - minimalistic-v2
    steps:
      - name: Checkout source
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          fetch-depth: 0
      - name: Get shared actions
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          repository: 'DoodleScheduling/actions'
          ref: v3
          path: './.actions'
          token: ${{ secrets.GH_ACTIONS }}
      - uses: ./.actions/renovate
        with:
          lib-grafana-private-key: ${{ secrets.PRIVATE_SSH_KEY_LIB_GRAFANA }}
          token: ${{ secrets.GH_ACTIONS }}
    timeout-minutes: 45
